server:
    port: 81
spring:
    application:
        name: authorization-server
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
#    redis:
#        host: 106.52.67.250
#        port: 6380
#        password: 123456*
